modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="umccore"
version="1.1.1"
displayName="UMC Core [FORGE]"
credits="Its Mr . Shmello"
displayURL="https://www.theumcnetwork.com"
logoFile="logo.png"
authors="UMC Network"
description='''
UMC Core mod
'''

[[dependencies.umccore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.umccore]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.umccore]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

